#!/usr/bin/env bash
#
# Deploy PulseRun Core to Stellar testnet, in dependency order, and print the
# resulting contract ids. Deploying this script does not touch mainnet.
#
# Order matters: the escrow settles in a token, so the token (mock_token, for
# testnet only) is deployed first and its id is passed nowhere at deploy time —
# the token address is supplied per job to create_job.
#
# Requires: stellar-cli (https://github.com/stellar/stellar-cli)
# Usage:    ./scripts/deploy-testnet.sh
set -euo pipefail

NETWORK="testnet"
IDENTITY="${STELLAR_IDENTITY:-pulserun-deployer}"
DISPUTE_WINDOW_SECS="${DISPUTE_WINDOW_SECS:-86400}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${ROOT_DIR}/docs/deployments/testnet.env"

command -v stellar >/dev/null 2>&1 || {
  echo "error: stellar-cli not found. Install: cargo install --locked stellar-cli --features opt" >&2
  exit 1
}

echo "==> Building contracts"
cd "${ROOT_DIR}"
stellar contract build

# Create and fund the deployer identity on testnet if it does not exist.
if ! stellar keys address "${IDENTITY}" >/dev/null 2>&1; then
  echo "==> Creating and funding identity '${IDENTITY}' on ${NETWORK}"
  stellar keys generate "${IDENTITY}" --network "${NETWORK}" --fund --overwrite
fi
ADMIN_ADDRESS="$(stellar keys address "${IDENTITY}")"
echo "    admin/deployer: ${ADMIN_ADDRESS}"

echo "==> Deploying mock_token (testnet only)"
TOKEN_ID="$(
  stellar contract deploy \
    --wasm target/wasm32v1-none/release/mock_token.wasm \
    --network "${NETWORK}" \
    --source "${IDENTITY}"
)"
echo "    mock_token: ${TOKEN_ID}"

echo "==> Deploying pulserun_escrow"
ESCROW_ID="$(
  stellar contract deploy \
    --wasm target/wasm32v1-none/release/pulserun_escrow.wasm \
    --network "${NETWORK}" \
    --source "${IDENTITY}"
)"
echo "    pulserun_escrow: ${ESCROW_ID}"

echo "==> Initializing escrow (dispute window ${DISPUTE_WINDOW_SECS}s)"
stellar contract invoke \
  --id "${ESCROW_ID}" \
  --network "${NETWORK}" \
  --source "${IDENTITY}" \
  -- init \
  --admin "${ADMIN_ADDRESS}" \
  --dispute_window_secs "${DISPUTE_WINDOW_SECS}"

mkdir -p "$(dirname "${OUT_FILE}")"
cat >"${OUT_FILE}" <<EOF
# Generated by scripts/deploy-testnet.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NETWORK=${NETWORK}
ADMIN_ADDRESS=${ADMIN_ADDRESS}
DISPUTE_WINDOW_SECS=${DISPUTE_WINDOW_SECS}
PULSEESCROW_ID=${ESCROW_ID}
MOCKTOKEN_ID=${TOKEN_ID}
EOF

cat <<EOF

================================================================
 PulseRun Core — ${NETWORK} deployment complete
----------------------------------------------------------------
 PULSEESCROW_ID=${ESCROW_ID}
 MOCKTOKEN_ID=${TOKEN_ID}
 ADMIN_ADDRESS=${ADMIN_ADDRESS}
 DISPUTE_WINDOW_SECS=${DISPUTE_WINDOW_SECS}
----------------------------------------------------------------
 Explorer: https://stellar.expert/explorer/${NETWORK}/contract/${ESCROW_ID}
 Env written to: ${OUT_FILE}
 Record these in docs/deployments/testnet.md.
================================================================
EOF
